import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/components/Providers";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} bg-white text-black dark:bg-gray-900 dark:selection:bg-gray-600 dark:text-white h-full selection:bg-gray-300`}
      >
        <Providers>
          <Navbar />

          <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
            {children}
          </main>

          <Link
            href="https://nadim.vercel.app"
            className="max-w-3xl mx-auto text-gray-300 block text-md my-6 px-4 sm:px-6 lg:px-8"
          >
            Developed by Nadim Chowdhury
          </Link>
        </Providers>
      </body>
    </html>
  );
}
